version: "3"

services:
  element:
    build:
      context: ./
    networks:
      default: {}
    image: ${IMAGE_NAME-element}
    container_name: ${CONTAINER_NAME-element}
    restart: 'no'
    ports:
      - "${PORT-85}:80"
    volumes:
      - ${ELEMENT_DIR-./}:/var/www/element
    working_dir: ${WORKDIR-/var/www/element}
networks:
  default:
    external: true
    name: ${NETWORK-element_default}